// Code generated by hertz generator.

package main

import (
	"flag"
	"github.com/CloudGoSight/cloudgosight_api/bootstrap"
	"github.com/CloudGoSight/cloudgosight_api/conf"
	"github.com/CloudGoSight/cloudgosight_api/middleware"
	"github.com/CloudGoSight/cloudgosight_api/util"
	"github.com/cloudwego/hertz/pkg/app/server"
	"io/fs"
)

var (
	isEject    bool
	confPath   string // 服务器存一个配置文件
	scriptName string
	staticZip  string
	staticFS   fs.FS
)

func init() {
	// 默认文件是go程序目录下新建conf.ini
	flag.StringVar(&confPath, "conf", util.RelativePath("conf.ini"), "config path")
	flag.BoolVar(&isEject, "eject", false, "eject frontend files")
	flag.Parse()

	bootstrap.Init(confPath, staticFS)

}

func main() {
	// 41943040000 = 4 * 1024 * 1024 * 10000 = 40000M ≈ 40GB
	h := server.Default(server.WithHostPorts(":8889"), server.WithMaxRequestBodySize(41943040000))

	if isEject {
		// todo
	}

	if scriptName == "" {
		// todo
	}

	if conf.SystemConfig.Debug {

	}

	h.Use(middleware.Session("xxx"))
	h.Use(middleware.CurrentUser())
	h.Use(middleware.CacheControl())

	customizedRegister(h)
	h.Spin()
}
